### ISSUE TITLE
infinite loop of failing to get symbols from /usr/bin/bash

### ISSUE THREAD

**Issue by jdomke** [score-p/scorep_binding_python#58]
Hi,

I'll just throw a few infos at you, since I'm not sure what the root cause is, yet.
- OS: fedora 31 server (home is mounted nfs)
- gcc: 9.2.0
- score-p 6.0 build with libunwind 1.3.1 support
- self-compiled libwrapper for openblas
- python3.7 (comes with OS)
- scorep_binding_python commit 87ed06f6223a

Simple test case:
⇒  cat a.py 
```
import scorep
print("1")
```

Run command:
```
python3.7 -m scorep ./a.py
```

Problem 1: getting strange LD_PRELOAD errors:
```
ERROR: ld.so: object '/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/scorep-6.0-j5anb6726xhsgsjdgtseotbzvwmtn3rd/lib/libscorep_adapter_compiler_event.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

Problem 2: strange write errors (but folder exists and is writable):
```
[Score-P] src/measurement/scorep_runtime_management.c:440: Error: Unable to open file: Cannot write MANIFEST.md into '/home/domke/dl4fugaku/simple_kernels/scorep-measurement-tmp20200229_0808_426216785652414/MANIFEST.md'
```

Problem 3: infinite loop with errors about nm:
```
[Score-P] src/adapters/compiler/scorep_compiler_symbol_table_nm.c:119: Error: Error in execution of system command: Failed to get symbol table output using following command: '/usr/bin/nm -l /usr/bin/bash 2> scorep_nm_file.426216758993170_err > scorep_nm_file.426216758993170'. Function enter/exit will not be recorded. Consider providing the symbol table output in a file by exporting SCOREP_NM_SYMBOLS
```

Workaround:
All those problems simply go away if I set SCOREP_ENABLE_UNWINDING=true, but only because i saw in the score-p code that i can prevent it from calling scorep_compiler_load_symbols, which is the reason for problem 3.

Tracing of common c/c++ binaries seems to work out of the box and without the workaround, so I expect some strange incompatibility with scorep+libunwind+python, but I cannot pin down the true cause.

Best,
jens

**Comment by AndreasGocht** [comment]
Hey,

Please check if you build Score-P with the gcc compiler plugin and `--enable-shared`.
Please also post the output of `scorep-info config-summary`.
If you are using Ubuntu please also try with the Score-P Ubuntu Package: https://launchpad.net/~andreasgocht/+archive/ubuntu/scorep .

Best,

Andreas

**Comment by jdomke** [comment]
seems to be a yes to both your questions
```
Configure command:
  /tmp/domke/spack-stage/spack-stage-scorep-6.0-p6xvlymtjvwhvhbwxaieygo4tu6rk3t2/spack-src/configure \
                                '--prefix=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/scorep-6.0-p6xvlymtjvwhvhbwxaieygo4tu6rk3t2' \
                                '--with-otf2=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/otf2-2.2-lyskysfkbx5yhxwsqnptgop4ni5id6rn/bin' \
                                '--with-opari2=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/opari2-2.0.5-zbdrb5klg5i7iohwm4dzs6itofgaloca/bin' \
                                '--enable-shared' \
                                '--disable-online-access' \
                                '--with-nocross-compiler-suite=gcc' \
                                '--with-cubew=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubew-4.4.3-hhbegac4ghjkarrlxqxeumbvk3wrcn6p/bin' \
                                '--with-cubelib=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubelib-4.4.4-7agwxlyc3mejz67nhjsufx7ulvjmtfdo/bin' \
                                '--with-papi-header=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/papi-5.7.0-ccvcpzcvz6vbfsu2sykmqxpnslh4s5ha/include' \
                                '--with-papi-lib=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/papi-5.7.0-ccvcpzcvz6vbfsu2sykmqxpnslh4s5ha/lib' \
                                '--without-shmem' \
                                '--with-mpi' \
                                '--with-mpi=openmpi' \
                                'CFLAGS=-fPIC' \
                                'CXXFLAGS=-fPIC' \
                                'MPICC=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpicc' \
                                'MPICXX=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpic++' \
                                'MPIF77=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpif77' \
                                'MPIFC=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpif90'

Loaded modules:
  No modules loaded

Configuration summary:
  Score-P 6.0:
    Platform:                   linux (auto detected)
    Cross compiling:            no (auto detected)
    Machine name:               Linux
    otf2 support:               yes, using external via /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/otf2-2.2-lyskysfkbx5yhxwsqnptgop4ni5id6rn/bin/otf2-config
    opari2 support:             yes, using external via /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/opari2-2.0.5-zbdrb5klg5i7iohwm4dzs6itofgaloca/bin/opari2-config
    cubew support:              yes, using external via /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubew-4.4.3-hhbegac4ghjkarrlxqxeumbvk3wrcn6p/bin/cubew-config
    cubelib support:            yes, using external via /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubelib-4.4.4-7agwxlyc3mejz67nhjsufx7ulvjmtfdo/bin/cubelib-config
    SHMEM support:              no, explicitly disabled via --without-shmem

    Score-P (backend):
      C99 compiler used:        gcc
      Link mode:                static=yes, shared=yes
      Pthread support:          yes, using gcc -pthread 
      compiler constructor:     yes, using attribute syntax without arguments
      Platform:                 linux (provided)
      TLS support:              yes, using __thread and the initial-exec model
      PAPI support:             yes
      metric perf support:      yes
      Unwinding support:        no, missing libunwind support
        libunwind support:      no
      Sampling support:         no
      getrusage support:        yes
      RUSAGE_THREAD support:    yes, using -D_GNU_SOURCE
      dlfcn support:            yes, using -ldl
      OpenCL support:           no
        libOpenCL support:      no
      I/O Recording features:
        POSIX I/O support:      yes
        POSIX asynchronous I/O support:
                                yes, using -lrt
      OTF2 features:
        SIONlib support:        no
      CUDA support:             no
        libcudart support:      no
        libcuda support:        no
        libcupti support:       no
        CUPTI async support:    no
        CUDA version >= 6.0:    no
      OpenACC support:          no
      Mount point extraction:   yes
      OpenMP support:           yes, using -fopenmp
        OpenMP pomp_tpd:        yes
        OpenMP ancestry:        yes
      PDT support:              no
      Cobi support:             no
      Timer support:            yes, providing gettimeofday, clock_gettime(CLOCK_MONOTONIC_RAW), tsc (X86_64)
        Timer LDFLAGS:          -lm
      libbfd support:           no
      compiler instrumentation: yes, using GCC plug-in with support for compile-time filtering
      Online access support:    no, explicitly disabled via --disable-online-access
      Memory tracking support:  yes
      Compiler wrappers:        scorep-gcc scorep-g++ scorep-gfortran scorep-mpicc scorep-mpic++ scorep-mpif77 scorep-mpif90 
      User library wrappers support:
                                yes

    Score-P (GCC plug-in):
      GCC plug-in support:      yes, using the C++ compiler and -I/usr/lib/gcc/x86_64-redhat-linux/9/plugin/include
      Compiler used:            g++ -std=c++11

    Score-P (libwrap):
      Library wrapper support:  yes, using /usr/bin/llvm-config
      C compiler used:          /usr/bin/clang
      C++ compiler used:        /usr/bin/clang++

    Score-P (MPI backend):
      Link mode:                static=yes, shared=yes
      C99 compiler works:       yes, using /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpicc
      C++ compiler works:       yes, using /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpic++
      F77 compiler works:       yes, using /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpif77
      F90 compiler works:       yes, using /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpif90
      Library used for MPI:     
      TLS support:              yes, using __thread and the initial-exec model
      PAPI support:             yes
      metric perf support:      yes
      Unwinding support:        no, missing libunwind support
        libunwind support:      no
      Sampling support:         no
      getrusage support:        yes
      RUSAGE_THREAD support:    yes, using -D_GNU_SOURCE
      dlfcn support:            yes, using -ldl
      OpenCL support:           no
        libOpenCL support:      no
        Platform:               linux (provided)
      I/O Recording features:
        POSIX I/O support:      yes
        POSIX asynchronous I/O support:
                                yes, using -lrt
      CUDA support:             no
        libcudart support:      no
        libcuda support:        no
        libcupti support:       no
        CUPTI async support:    no
        CUDA version >= 6.0:    no
      OpenACC support:          no
      Mount point extraction:   yes
      OpenMP support:           yes, using -fopenmp
        OpenMP pomp_tpd:        yes
        OpenMP ancestry:        yes
      PDT MPI instrumentation:  yes, if PDT available
      Timer support:            yes, providing gettimeofday, clock_gettime(CLOCK_MONOTONIC_RAW), tsc (X86_64)
        Timer LDFLAGS:          -lm
      libbfd support:           no
      compiler instrumentation: yes, using GCC plug-in with support for compile-time filtering
      Online access support:    no, explicitly disabled via --disable-online-access
      Memory tracking support:  yes
      User library wrappers support:
                                yes

    Score-P (score):
      C compiler used:          gcc 
      C++ compiler used:        g++
      cube c++ library support: yes, using -I/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubelib-4.4.4-7agwxlyc3mejz67nhjsufx7ulvjmtfdo/include/cubelib  -L/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubelib-4.4.4-7agwxlyc3mejz67nhjsufx7ulvjmtfdo/lib -Wl,-rpath -Wl,/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubelib-4.4.4-7agwxlyc3mejz67nhjsufx7ulvjmtfdo/lib  -lcube4 -lz
```

**Comment by AndreasGocht** [comment]
Interesting. According to the config, it should work. However, there are a few frictions, with the information of your initial post.

You said you build with `libunwind 1.3.1` support. However, the config says:
```
      Unwinding support:        no, missing libunwind support
        libunwind support:      no
```

Moreover, the prefix spcified `/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/scorep-6.0-p6xvlymtjvwhvhbwxaieygo4tu6rk3t2` and the actuall searchpath `/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/scorep-6.0-j5anb6726xhsgsjdgtseotbzvwmtn3rd/lib/` do not match.

Are you sure that this is the same Score-P version, that you used with the bindings? Please be aware, that the Score-P that is loaded during Runtime matters, and should be the same as the one during compile time.

If you are sure, that this is the same Version, please post the output of `ll /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/scorep-6.0-j5anb6726xhsgsjdgtseotbzvwmtn3rd/lib/`.

**Comment by jdomke** [comment]
ups, sorry, was the wrong scorep version, i have two (build the latter without unwind because of this issue), the one with seem to not have the plugin support, see:
```
Configure command:
  /tmp/domke/spack-stage/spack-stage-scorep-6.0-j5anb6726xhsgsjdgtseotbzvwmtn3rd/spack-src/configure \
                                '--prefix=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/scorep-6.0-j5anb6726xhsgsjdgtseotbzvwmtn3rd' \
                                '--with-otf2=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/otf2-2.2-lyskysfkbx5yhxwsqnptgop4ni5id6rn/bin' \
                                '--with-opari2=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/opari2-2.0.5-zbdrb5klg5i7iohwm4dzs6itofgaloca/bin' \
                                '--enable-shared' \
                                '--disable-online-access' \
                                '--with-nocross-compiler-suite=gcc' \
                                '--with-cubew=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubew-4.4.3-hhbegac4ghjkarrlxqxeumbvk3wrcn6p/bin' \
                                '--with-cubelib=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubelib-4.4.4-7agwxlyc3mejz67nhjsufx7ulvjmtfdo/bin' \
                                '--with-papi-header=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/papi-5.7.0-ccvcpzcvz6vbfsu2sykmqxpnslh4s5ha/include' \
                                '--with-papi-lib=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/papi-5.7.0-ccvcpzcvz6vbfsu2sykmqxpnslh4s5ha/lib' \
                                '--with-libunwind=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/libunwind-1.3.1-y4gpoiwhg7zrijybvpjfdzplffal6enx' \
                                '--without-shmem' \
                                '--with-mpi' \
                                '--with-mpi=openmpi' \
                                'CFLAGS=-fPIC' \
                                'CXXFLAGS=-fPIC' \
                                'MPICC=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpicc' \
                                'MPICXX=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpic++' \
                                'MPIF77=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpif77' \
                                'MPIFC=/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpif90'

Loaded modules:
  No modules loaded

Configuration summary:
  Score-P 6.0:
    Platform:                   linux (auto detected)
    Cross compiling:            no (auto detected)
    Machine name:               Linux
    otf2 support:               yes, using external via /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/otf2-2.2-lyskysfkbx5yhxwsqnptgop4ni5id6rn/bin/otf2-config
    opari2 support:             yes, using external via /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/opari2-2.0.5-zbdrb5klg5i7iohwm4dzs6itofgaloca/bin/opari2-config
    cubew support:              yes, using external via /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubew-4.4.3-hhbegac4ghjkarrlxqxeumbvk3wrcn6p/bin/cubew-config
    cubelib support:            yes, using external via /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubelib-4.4.4-7agwxlyc3mejz67nhjsufx7ulvjmtfdo/bin/cubelib-config
    SHMEM support:              no, explicitly disabled via --without-shmem

    Score-P (backend):
      C99 compiler used:        gcc
      Link mode:                static=yes, shared=yes
      Pthread support:          yes, using gcc -pthread 
      compiler constructor:     yes, using attribute syntax without arguments
      Platform:                 linux (provided)
      TLS support:              yes, using __thread and the initial-exec model
      PAPI support:             yes
      metric perf support:      yes
      Unwinding support:        yes
        libunwind support:      yes, using -D_GNU_SOURCE -I/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/libunwind-1.3.1-y4gpoiwhg7zrijybvpjfdzplffal6enx/include -L/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/libunwind-1.3.1-y4gpoiwhg7zrijybvpjfdzplffal6enx/lib -R/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/libunwind-1.3.1-y4gpoiwhg7zrijybvpjfdzplffal6enx/lib -lunwind
      Sampling support:         yes, using -D_GNU_SOURCE, sa_sigaction
      getrusage support:        yes
      RUSAGE_THREAD support:    yes, using -D_GNU_SOURCE
      dlfcn support:            yes, using -ldl
      OpenCL support:           no
        libOpenCL support:      no
      I/O Recording features:
        POSIX I/O support:      yes
        POSIX asynchronous I/O support:
                                yes, using -lrt
      OTF2 features:
        SIONlib support:        no
      CUDA support:             no
        libcudart support:      no
        libcuda support:        no
        libcupti support:       no
        CUPTI async support:    no
        CUDA version >= 6.0:    no
      OpenACC support:          no
      Mount point extraction:   yes
      OpenMP support:           yes, using -fopenmp
        OpenMP pomp_tpd:        yes
        OpenMP ancestry:        yes
      PDT support:              no
      Cobi support:             no
      Timer support:            yes, providing gettimeofday, clock_gettime(CLOCK_MONOTONIC_RAW), tsc (X86_64)
        Timer LDFLAGS:          -lm
      libbfd support:           no
      compiler instrumentation: yes, using nm
      Online access support:    no, explicitly disabled via --disable-online-access
      Memory tracking support:  yes
      Compiler wrappers:        scorep-gcc scorep-g++ scorep-gfortran scorep-mpicc scorep-mpic++ scorep-mpif77 scorep-mpif90 
      User library wrappers support:
                                yes

    Score-P (GCC plug-in):
      GCC plug-in support:      no, missing plug-in headers, please install

    Score-P (libwrap):
      Library wrapper support:  yes, using /usr/bin/llvm-config
      C compiler used:          /usr/bin/clang
      C++ compiler used:        /usr/bin/clang++

    Score-P (MPI backend):
      Link mode:                static=yes, shared=yes
      C99 compiler works:       yes, using /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpicc
      C++ compiler works:       yes, using /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpic++
      F77 compiler works:       yes, using /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpif77
      F90 compiler works:       yes, using /home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/openmpi-3.1.5-xdkjeagq4yeftkoocyeaf5eni46iox3z/bin/mpif90
      Library used for MPI:     
      TLS support:              yes, using __thread and the initial-exec model
      PAPI support:             yes
      metric perf support:      yes
      Unwinding support:        yes
        libunwind support:      yes, using -D_GNU_SOURCE -I/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/libunwind-1.3.1-y4gpoiwhg7zrijybvpjfdzplffal6enx/include -L/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/libunwind-1.3.1-y4gpoiwhg7zrijybvpjfdzplffal6enx/lib -R/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/libunwind-1.3.1-y4gpoiwhg7zrijybvpjfdzplffal6enx/lib -lunwind
      Sampling support:         yes, using -D_GNU_SOURCE, sa_sigaction
      getrusage support:        yes
      RUSAGE_THREAD support:    yes, using -D_GNU_SOURCE
      dlfcn support:            yes, using -ldl
      OpenCL support:           no
        libOpenCL support:      no
        Platform:               linux (provided)
      I/O Recording features:
        POSIX I/O support:      yes
        POSIX asynchronous I/O support:
                                yes, using -lrt
      CUDA support:             no
        libcudart support:      no
        libcuda support:        no
        libcupti support:       no
        CUPTI async support:    no
        CUDA version >= 6.0:    no
      OpenACC support:          no
      Mount point extraction:   yes
      OpenMP support:           yes, using -fopenmp
        OpenMP pomp_tpd:        yes
        OpenMP ancestry:        yes
      PDT MPI instrumentation:  yes, if PDT available
      Timer support:            yes, providing gettimeofday, clock_gettime(CLOCK_MONOTONIC_RAW), tsc (X86_64)
        Timer LDFLAGS:          -lm
      libbfd support:           no
      compiler instrumentation: yes, using nm
      Online access support:    no, explicitly disabled via --disable-online-access
      Memory tracking support:  yes
      User library wrappers support:
                                yes

    Score-P (score):
      C compiler used:          gcc 
      C++ compiler used:        g++
      cube c++ library support: yes, using -I/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubelib-4.4.4-7agwxlyc3mejz67nhjsufx7ulvjmtfdo/include/cubelib  -L/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubelib-4.4.4-7agwxlyc3mejz67nhjsufx7ulvjmtfdo/lib -Wl,-rpath -Wl,/home/domke/spack/opt/spack/linux-fedora31-skylake_avx512/gcc-9.2.1/cubelib-4.4.4-7agwxlyc3mejz67nhjsufx7ulvjmtfdo/lib  -lcube4 -lz
```

**Comment by AndreasGocht** [comment]
Please also add the output of `scorep-config --preload-libs` and check if the specified files exist.

Best,

Andreas

**Comment by AndreasGocht** [comment]
Ah ok. Then the missing plugin support is the problem. I introduced the check for the plugin during the installation of the binding with the latest commit a2a4ab4 as part of #57 . Please try to rebuild Score-P with the gcc-plugin support.

**Comment by jdomke** [comment]
Ok, rebuilding the scorep version has worked and fixed my initial bug, and moving to latest commit works as well. Thanks a lot!
